### PR TITLE
fix py312 on osx

### PR DESCRIPTION
**Pull request by nilsnolde**
it errored out with some old boost stuff, so I'll try to update it to 1.83.0, same as current upstream vcpkg

### CODE REVIEW

**Comment by nilsnolde** [comment]
meeh, won't work with conan 1.x. this repo didn't switch yet to vcpkg.. I'll drop this for now, soon the bindings will be published from the upstream valhalla repo.

**Comment by thomthom** [comment]
New to this project. Trying to orient myself as it looks promising for a potential project. I was curious to try to build the project myself to learn more. Ran into the same issue with python 3.12 and started poking around in the issues.

> meeh, won't work with conan 1.x. this repo didn't switch yet to vcpkg
There is a desire to migrate to vcpgk?

>  soon the bindings will be published from the upstream valhalla repo.
What are these bindings? Something this project used to provide that now will come from upstream?

**Comment by nilsnolde** [comment]
> What are these bindings?

this project :smile: it's python bindings to the c++ valhalla library..

the plan is to move the packaging to the upstream valhalla repo. that's the only thing this repo is really doing. I once had plans to do a few more things with it but so far I always ended up contributing enhancements back upstream. so there's no real need for an extra project and we can build & publish from valhalla repo. that'll take a while though, don't think I'll manage that in the next weeks.

**Comment by thomthom** [comment]
Ah, ok. Thank you for the insight. I'll keep an eye on the progress with that. I really liked the idea of using Valhalla directly from a language, like Python, instead of communicating back to a REST API server from the front end. And simplifying the distribution as you describe also sounds great.

So I take it that in terms of contributing back it's better to focus on Valhalla itself than this project?

**Comment by nilsnolde** [comment]
> So I take it that in terms of contributing back it's better to focus on Valhalla itself than this project?

yes for sure:)

**Pull request closed without merging**
